apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: tutum/hello-world
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: microservice-svc
 
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: microservice
  type: NodePort
