apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-message
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-message
  template:
    metadata:
      labels:
        app: microservice-message
    spec:
      containers:
      - name: microservice-message
        image: rajpalsinghd/test:tagVersion
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: microservice-message-svc
 
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: microservice-message
  type: NodePort
