apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-message1
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-message1
  template:
    metadata:
      labels:
        app: microservice-message1
    spec:
      containers:
      - name: microservice-message1
        image: yashtech/microservice
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: microservice-message-svc1
 
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: microservice-message1
  type: NodePort
